recipe_titles = [
    "Creamy Mushroom Risotto",
    "Spicy Thai Curry Noodles",
    "Grilled Teriyaki Salmon",
    "Mediterranean Quinoa Salad",
    "Cheesy Stuffed Bell Peppers",
    "Lemon Herb Roast Chicken",
    "Vegetarian Taco Bowls",
    "Garlic Butter Shrimp Linguine",
    "Sweet and Sour Tofu Stir-Fry",
    "Apple Cinnamon Pancakes",
    "BBQ Pulled Pork Sliders",
    "Roasted Beet and Goat Cheese Salad",
    "Cajun Blackened Catfish",
    "Caprese Stuffed Portobello Mushrooms",
    "Teriyaki Pineapple Fried Rice",
    "Creamy Sun-dried Tomato Pasta",
    "Moroccan Chickpea Stew",
    "Blueberry Almond Oatmeal Smoothie",
    "Spinach and Feta Stuffed Chicken Breast",
    "Chocolate Raspberry Tart",
]

recipe_descriptions = [
    "A creamy and flavorful risotto with sautéed mushrooms.",
    "A zesty and aromatic noodle dish with a kick of Thai spices.",
    "Juicy salmon marinated in teriyaki sauce and grilled to perfection.",
    "A refreshing salad packed with Mediterranean flavors and quinoa.",
    "Colorful bell peppers stuffed with a cheesy and savory filling.",
    "Tender roast chicken infused with lemon and aromatic herbs.",
    "A hearty bowl of vegetarian goodness, complete with all your taco favorites.",
    "Delicate shrimp tossed in garlicky butter sauce served over linguine.",
    "Crispy tofu and vibrant vegetables in a tangy sweet and sour sauce.",
    "Fluffy pancakes infused with apple and cinnamon flavors.",
    "Mini sliders featuring slow-cooked BBQ pulled pork in soft buns.",
    "Roasted beets paired with creamy goat cheese on a bed of greens.",
    "Cajun-spiced catfish fillets with a rich and smoky flavor.",
    "Portobello mushrooms stuffed with fresh mozzarella, tomatoes, and basil.",
    "A fusion of teriyaki and pineapple flavors in a satisfying fried rice dish.",
    "A luscious pasta dish featuring sun-dried tomatoes and a creamy sauce.",
    "A fragrant and hearty stew made with Moroccan spices and chickpeas.",
    "A nutritious and delicious smoothie blending blueberries and almonds.",
    "Chicken breasts filled with spinach and feta, baked to perfection.",
    "Decadent tart with a chocolate base and a burst of raspberry sweetness.",
]

recipe_times = [
    30,
    25,
    20,
    15,
    10,
    5,
    30,
    25,
    20,
    15,
    10,
    5,
    30,
    25,
    20,
    15,
    10,
    5,
    30,
    25,
]

recipe_prices = [
    9.99,
    8.99,
    7.99,
    6.99,
    5.99,
    4.99,
    9.99,
    8.99,
    7.99,
    6.99,
    5.99,
    4.99,
    9.99,
    8.99,
    7.99,
    6.99,
    5.99,
    4.99,
    9.99,
    8.99,
]
